site_name: Traefik 文档
site_description: Traefik Documentation Chinese Edition
site_author: containo.us
site_url: https://traefik-doc.livedig.com
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/sunadm/traefik'

docs_dir: 'content'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  favicon: assets/img/traefik.icon.png
  logo: assets/img/traefik.logo.png
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; 2016-2020 Containous"

google_analytics:
  - 'UA-526900-5'
  - 'traefik-docs.livedig.com'

extra_css:
  - assets/styles/extra.css # Our custom styles
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/js/extra.js

plugins:
  - search
  - exclude:
      glob:
        - "**/include-*.md"

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
#  - markdown_include.include:
#      base_path: content/includes/
#      encoding: utf-8
  - toc:
      permalink: true

# Page tree
nav:
  - '欢迎': 'index.md'
  - '入门':
      - '概念' : 'getting-started/concepts.md'
      - '快速入门': 'getting-started/quick-start.md'
      - '配置介绍': 'getting-started/configuration-overview.md'
      - '安装Traefik': 'getting-started/install-traefik.md'
  - '配置发现':
      - '概览': 'providers/overview.md'
      - 'Docker': 'providers/docker.md'
      - 'Kubernetes IngressRoute': 'providers/kubernetes-crd.md'
      - 'Kubernetes Ingress': 'providers/kubernetes-ingress.md'
      - 'Consul Catalog': 'providers/consul-catalog.md'
      - 'Marathon': 'providers/marathon.md'
      - 'Rancher': 'providers/rancher.md'
      - '文件': 'providers/file.md'
      - 'Consul': 'providers/consul.md'
      - 'Etcd': 'providers/etcd.md'
      - 'ZooKeeper': 'providers/zookeeper.md'
      - 'Redis': 'providers/redis.md'
  - '路由和负载均衡':
      - '概览': 'routing/overview.md'
      - '入口点EntryPoints': 'routing/entrypoints.md'
      - '路由器Routers': 'routing/routers/index.md'
      - '服务Services': 'routing/services/index.md'
      - '提供者Providers':
          - 'Docker': 'routing/providers/docker.md'
          - 'Kubernetes IngressRoute': 'routing/providers/kubernetes-crd.md'
          - 'Kubernetes Ingress': 'routing/providers/kubernetes-ingress.md'
          - 'Consul Catalog': 'routing/providers/consul-catalog.md'
          - 'Marathon': 'routing/providers/marathon.md'
          - 'Rancher': 'routing/providers/rancher.md'
          - 'KV': 'routing/providers/kv.md'
  - 'HTTPS和TLS':
      - '概览': 'https/overview.md'
      - 'TLS': 'https/tls.md'
      - 'Let''s Encrypt': 'https/acme.md'
  - '中间件':
      - '概览': 'middlewares/overview.md'
      - 'AddPrefix': 'middlewares/addprefix.md'
      - 'BasicAuth': 'middlewares/basicauth.md'
      - 'Buffering': 'middlewares/buffering.md'
      - 'Chain': 'middlewares/chain.md'
      - 'CircuitBreaker': 'middlewares/circuitbreaker.md'
      - 'Compress': 'middlewares/compress.md'
      - 'ContentType': 'middlewares/contenttype.md'
      - 'DigestAuth': 'middlewares/digestauth.md'
      - 'Errors': 'middlewares/errorpages.md'
      - 'ForwardAuth': 'middlewares/forwardauth.md'
      - 'Headers': 'middlewares/headers.md'
      - 'IpWhitelist': 'middlewares/ipwhitelist.md'
      - 'InFlightReq': 'middlewares/inflightreq.md'
      - 'PassTLSClientCert': 'middlewares/passtlsclientcert.md'
      - 'RateLimit': 'middlewares/ratelimit.md'
      - 'RedirectRegex': 'middlewares/redirectregex.md'
      - 'RedirectScheme': 'middlewares/redirectscheme.md'
      - 'ReplacePath': 'middlewares/replacepath.md'
      - 'ReplacePathRegex': 'middlewares/replacepathregex.md'
      - 'Retry': 'middlewares/retry.md'
      - 'StripPrefix': 'middlewares/stripprefix.md'
      - 'StripPrefixRegex': 'middlewares/stripprefixregex.md'
  - 'Operations':
      - 'CLI': 'operations/cli.md'
      - 'Dashboard' : 'operations/dashboard.md'
      - 'API': 'operations/api.md'
      - 'Ping': 'operations/ping.md'
  - '可观测性':
      - '日志': 'observability/logs.md'
      - '访问日志': 'observability/access-logs.md'
      - '指标Metrics':
          - '概览': 'observability/metrics/overview.md'
          - 'Datadog': 'observability/metrics/datadog.md'
          - 'InfluxDB': 'observability/metrics/influxdb.md'
          - 'Prometheus': 'observability/metrics/prometheus.md'
          - 'StatsD': 'observability/metrics/statsd.md'
      - '追踪Tracing':
          - '概览': 'observability/tracing/overview.md'
          - 'Jaeger': 'observability/tracing/jaeger.md'
          - 'Zipkin': 'observability/tracing/zipkin.md'
          - 'Datadog': 'observability/tracing/datadog.md'
          - 'Instana': 'observability/tracing/instana.md'
          - 'Haystack': 'observability/tracing/haystack.md'
          - 'Elastic': 'observability/tracing/elastic.md'
  - '用户指南':
      - 'Kubernetes以及Let''s Encrypt': 'user-guides/crd-acme/index.md'
      - 'gRPC示例': 'user-guides/grpc.md'
      - 'Marathon': 'user-guides/marathon.md'
      - 'Docker':
        - '基础示例': 'user-guides/docker-compose/basic-example/index.md'
        - 'HTTPS with Let''s Encrypt':
          - 'TLS 挑战': 'user-guides/docker-compose/acme-tls/index.md'
          - 'HTTP 挑战': 'user-guides/docker-compose/acme-http/index.md'
          - 'DNS 挑战': 'user-guides/docker-compose/acme-dns/index.md'
  - '迁移':
      - 'Traefik v2 小迁移': 'migration/v2.md'
      - 'Traefik v1 到 v2': 'migration/v1-to-v2.md'
  - '贡献':
      - '谢谢你！': 'contributing/thank-you.md'
      - '提交Issues': 'contributing/submitting-issues.md'
      - '提交PRs': 'contributing/submitting-pull-requests.md'
      - '安全': 'contributing/submitting-security-issues.md'
      - '构建及测试': 'contributing/building-testing.md'
      - '文档': 'contributing/documentation.md'
      - '数据收集': 'contributing/data-collection.md'
      - 'Advocating': 'contributing/advocating.md'
      - '维护者': 'contributing/maintainers.md'
#  - 'Glossary': 'glossary.md'
  - '参考':
      - '静态配置':
          - '概览': 'reference/static-configuration/overview.md'
          - '文件': 'reference/static-configuration/file.md'
          - 'CLI': 'reference/static-configuration/cli.md'
          - '环境变量': 'reference/static-configuration/env.md'
      - '动态配置':
        - '文件': 'reference/dynamic-configuration/file.md'
        - 'Docker': 'reference/dynamic-configuration/docker.md'
        - 'Kubernetes CRD': 'reference/dynamic-configuration/kubernetes-crd.md'
        - 'Consul Catalog': 'reference/dynamic-configuration/consul-catalog.md'
        - 'Marathon': 'reference/dynamic-configuration/marathon.md'
        - 'Rancher': 'reference/dynamic-configuration/rancher.md'
        - 'KV': 'reference/dynamic-configuration/kv.md'
